### ISSUE TITLE
Rotation "crash"

### ISSUE THREAD

**Issue by FrauH0lle** [virtualguywithabowtie/surface-orientation#1]
The screen switches orientation only once and results in the following error:
`(orientation:9132): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/orientation_applet/orientation_controller.py", line 155, in run
    data = self.fetch()
  File "/usr/lib/python3.6/site-packages/orientation_applet/orientation_controller.py", line 150, in fetch
    return self.mgr.get_orientation()
  File "/usr/lib/python3.6/site-packages/orientation_applet/orientation_controller.py", line 140, in get_orientation
    self.refreshtouch()
  File "/usr/lib/python3.6/site-packages/orientation_applet/orientation_controller.py", line 83, in refreshtouch
    subprocess.call(['xinput disable', touch], shell=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'xinput disable'
`

**Comment by JefeDavis** [comment]
new version released let me know if this fixes it

**Comment by FrauH0lle** [comment]
Thanks again! Rotation works now without any issue. Only 
`dk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`
is shown in terminal but it does not seem to have an effect on the functionality.
